# Generated by Django 4.1.7 on 2023-03-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('flavour', models.CharField(max_length=200)),
                ('price', models.PositiveBigIntegerField()),
                ('shape', models.CharField(max_length=250)),
                ('weight', models.CharField(max_length=200)),
                ('layer', models.PositiveIntegerField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
